devices:
    - name : INVERTER_1
      driver: abb_pvs800_tcp_modbustk
      measurement: SPP_1  # InfluxDB Measurement (Table) Name
      slave_id : 1     # this is the slave address number
      ip_address : 192.168.1.2   # IPv4 destination address
      port : 502  # destination port
    - name : INVERTER_2
      driver: abb_pvs800_tcp_modbustk
      measurement: SPP_1  
      slave_id : 1     
      ip_address : 192.168.1.3 
      port : 502